// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eForms.Domain.Context;

namespace eForms.Domain.Migrations
{
    [DbContext(typeof(eFormsContext))]
    [Migration("20210511082215_ADSI_View")]
    partial class ADSI_View
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
