// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eForms.Domain.Context;

namespace eForms.Domain.Migrations
{
    [DbContext(typeof(eFormsContext))]
    partial class eFormsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            //modelBuilder
            //    .HasAnnotation("Relational:MaxIdentifierLength", 128)
            //    .HasAnnotation("ProductVersion", "5.0.4")
            //    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);



            //modelBuilder.Entity(eForms.Domain.Models.ADSI, b =>
            //    {
            //        b.HasNoKey;
            //        b.ToView("vw_ADSI");
            //    });

            //modelBuilder.Entity<eForms.Domain.Models.ADSI>(
            //eb =>
            //{
            //    eb.HasNoKey();
            //    eb.ToView("vw_ADSI");

            //});
            //modelBuilder.Entity<eForms.Domain.Models.ADUser>(entity =>
            //{
            //    entity.HasNoKey();
            //    entity.ToView("vw_ADSI");
            //});
#pragma warning restore 612, 618
        }
    }
}
